In [1]:
import torch 
torch.__version__

'2.12.0+cpu'

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

cpu


## jupyter


In [3]:
tensor=torch.rand(size=(1,10,10))

In [4]:
tensor

tensor([[[0.9173, 0.5251, 0.9468, 0.7499, 0.2731, 0.4828, 0.3230, 0.7664,
          0.6554, 0.8718],
         [0.1687, 0.6657, 0.3321, 0.1691, 0.2476, 0.4957, 0.4002, 0.2677,
          0.8844, 0.1329],
         [0.0743, 0.8548, 0.8269, 0.4374, 0.9610, 0.7850, 0.0698, 0.0711,
          0.0967, 0.0909],
         [0.1230, 0.9620, 0.3586, 0.4085, 0.6184, 0.7410, 0.1780, 0.8016,
          0.8768, 0.7395],
         [0.8605, 0.5698, 0.4783, 0.0466, 0.2332, 0.6617, 0.3136, 0.4721,
          0.8171, 0.2097],
         [0.1950, 0.1837, 0.4564, 0.5650, 0.9848, 0.2210, 0.4914, 0.7578,
          0.9289, 0.4366],
         [0.2864, 0.3111, 0.4922, 0.5193, 0.3363, 0.9908, 0.9119, 0.9278,
          0.3029, 0.3564],
         [0.8539, 0.9018, 0.5253, 0.4421, 0.4556, 0.4097, 0.9808, 0.9824,
          0.9372, 0.3346],
         [0.5687, 0.0487, 0.4261, 0.5413, 0.8368, 0.1688, 0.8410, 0.7774,
          0.4757, 0.3027],
         [0.3015, 0.2984, 0.4470, 0.0471, 0.8038, 0.8627, 0.5711, 0.1800,
          0.3738,

In [5]:
arrange = torch.arange(0,10)

In [6]:
arrange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
gpu = torch.tensor([1,2,3],dtype=None,device="cpu")

In [8]:
gpu

tensor([1, 2, 3])

# Tensors ATRB

Tensore have 3 main ATR

--1- List or arr of intel 

--2- Dtype : data tpye of the tensor like int64 or float32 ...

--3-Device: which device does the tensor gets power from GPU, CPU, TPU and 
....



In [9]:
torch.accelerator.is_available()

#why no accelerator ?? maybe jupyter is limited!

False

# Arithmetic operations

In [10]:
tensor2=tensor.squeeze()#reducing dim
tensor2.shape

torch.Size([10, 10])

# transpose


In [11]:
#transpose matrix
tran_tensor=tensor.T
tran_tensor.shape

C:\Users\pc\AppData\Local\Temp\ipykernel_12944\2309542453.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4484.)
  tran_tensor=tensor.T


torch.Size([10, 10, 1])

# op

In [18]:
# dot prodcut 
y=tensor@tensor2
y=tensor.matmul(tensor2)
y.view()
# matmul(first tensor, second, output)

TypeError: view() received an invalid combination of arguments - got (), but expected one of:
 * (torch.dtype dtype)
 * (tuple of ints size)


In [15]:
# add_ ,.... suffix ops!


# you could use numpy arrs in pytorch tensors too
n=np.arr()
t= torch.from_numpy(n)

NameError: name 'np' is not defined

# reshape

# TENSORS ARE DONE
next step datasets and nns