In [29]:
import torch 
torch.__version__

'2.12.0+cpu'

In [30]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)

cpu


## jupyter


In [31]:
tensor=torch.rand(size=(1,10,10))

In [32]:
tensor

tensor([[[0.1394, 0.3274, 0.6547, 0.1304, 0.1417, 0.5271, 0.0686, 0.8718,
          0.7444, 0.7763],
         [0.4341, 0.7076, 0.9645, 0.1136, 0.4354, 0.8371, 0.2327, 0.9295,
          0.8073, 0.4184],
         [0.8978, 0.8921, 0.3808, 0.2399, 0.2551, 0.7092, 0.1784, 0.3136,
          0.1405, 0.9952],
         [0.2602, 0.2934, 0.9703, 0.4186, 0.2598, 0.4831, 0.9174, 0.1369,
          0.2760, 0.3503],
         [0.2773, 0.3924, 0.0324, 0.4012, 0.2853, 0.2113, 0.2779, 0.5967,
          0.4935, 0.2441],
         [0.4494, 0.1585, 0.6057, 0.7155, 0.9118, 0.0480, 0.0850, 0.7248,
          0.4617, 0.1960],
         [0.5031, 0.2815, 0.7591, 0.4441, 0.3887, 0.4413, 0.2861, 0.7056,
          0.5096, 0.8263],
         [0.8207, 0.1729, 0.0470, 0.6980, 0.6398, 0.4155, 0.1886, 0.8289,
          0.0336, 0.6410],
         [0.6925, 0.7993, 0.6531, 0.7390, 0.1607, 0.8816, 0.2361, 0.1637,
          0.2700, 0.8226],
         [0.7295, 0.3876, 0.2537, 0.9508, 0.9700, 0.2093, 0.6161, 0.5331,
          0.5174,

In [33]:
arrange = torch.arange(0,10)

In [34]:
arrange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
gpu = torch.tensor([1,2,3],dtype=None,device="cpu")

In [36]:
gpu

tensor([1, 2, 3])

# Tensors ATRB

Tensore have 3 main ATR

--1- List or arr of intel 

--2- Dtype : data tpye of the tensor like int64 or float32 ...

--3-Device: which device does the tensor gets power from GPU, CPU, TPU and 
....



In [37]:
torch.accelerator.is_available()

#why no accelerator ?? maybe jupyter is limited!

False

# Arithmetic operations

In [47]:
tensor2=tensor.squeeze()#reducing dim
tensor2.shape

torch.Size([10, 10])

# transpose


In [45]:
#transpose matrix
tran_tensor=tensor.T
tran_tensor.shape

torch.Size([10, 10, 1])

# op

In [52]:
# dot prodcut 
y=tensor@tensor2
y=tensor.matmul(tensor2)
# matmul(first tensor, second, output)

torch.Size([10, 10])

In [53]:
# add_ ,.... suffix ops!


# you could use numpy arrs in pytorch tensors too
n=np.arr()
t= torch.from_numpy(n)

# TENSORS ARE DONE
next step datasets and nns